### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ijf8090**
Changed script file name from dev-start.sh to dev-setup.sh. 
Updated dev-setup.sh to install drush, which is not provided with the base install.

### CODE REVIEW

**Comment by greggmarshall** [comment]
Why update the setup bash script and not just update the composer.json/composer.lock pair?  That way it is clear it is a dependency when looking at the code.

**Comment by greggmarshall** [comment]
I just ran the gitpod as it is now and it ran successfully and had drush installed.  I am confused why you would want/need to have drush installed again.

**Comment by ijf8090** [comment]
I'm trying to follow the instructions to do a local install.

**Comment by ijf8090** [comment]
per conversation w. Gregg, close this PR. He will open a new one to sync up local and gitpod processes

**Comment by jrosgiralt** [comment]
Thanks, per your request, I have closed this PR.

**Pull request closed without merging**
