### PR TITLE
Jordi/9/dootronics

### PR DESCRIPTION
**Pull request by jrosgiralt**

### CODE REVIEW

**Comment by greggmarshall** [comment]
Automated checks (run the commands inside DDEV after using "ddev ssh" to shell inside) failing

**./vendor/bin/phpcs --standard="Drupal,DrupalPractice" --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md,yml web/modules/custom**

FILE: /var/www/html/web/modules/custom/lbd_lib/lbd_lib.info.yml
---------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AND 1 WARNING AFFECTING 2 LINES
---------------------------------------------------------------------------------------------------------------
 1 | WARNING | [ ] Remove "version" from the info file, it will be added by drupal.org packaging automatically
 6 | ERROR   | [x] Expected 1 newline at end of file; 2 found
---------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
---------------------------------------------------------------------------------------------------------------


FILE: /var/www/html/web/modules/custom/lbd_lib/lbd_lib.module
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 35 ERRORS AND 3 WARNINGS AFFECTING 29 LINES
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  5 | ERROR   | [x] Doc comment short description must end with a full stop
  5 | ERROR   | [x] Whitespace found at end of line
  8 | ERROR   | [x] There must be one blank line after the last USE statement; 2 found;
 12 | ERROR   | [x] Hook implementations must be documented with "Implements hook_example()."
 14 | ERROR   | [x] Expected 1 blank line before function; 2 found
 16 | ERROR   | [x] Line indented incorrectly; expected 2 spaces, found 4
 16 | ERROR   | [x] There should be no white space after an opening "{"
 16 | WARNING | [ ] Line exceeds 80 characters; contains 89 characters
 16 | ERROR   | [x] Comments may not appear after statements
 17 | ERROR   | [x] Line indented incorrectly; expected 4 spaces, found 6
 18 | ERROR   | [x] Line indented incorrectly; expected 4 spaces, found 6
 19 | ERROR   | [x] Line indented incorrectly; expected 4 spaces, found 6
 20 | ERROR   | [x] Line indented incorrectly; expected 4 spaces, found 6
 21 | ERROR   | [x] Line indented incorrectly; expected 4 spaces, found 6
 22 | ERROR   | [x] Line indented incorrectly; expected 2 spaces, found 4
 23 | ERROR   | [x] Whitespace found at end of line
 24 | ERROR   | [x] Expected 1 blank line after function; 3 found
 27 | ERROR   | [ ] More than 2 empty lines are not allowed
 29 | ERROR   | [x] Doc comment short description must end with a full stop
 31 | ERROR   | [ ] Description for the @return value must be on the next line
 33 | ERROR   | [x] Additional blank lines found at end of doc comment
 36 | WARNING | [x] 'TODO: Optimize this query' should match the format '@todo Fix problem X here.'
 36 | ERROR   | [x] Line indented incorrectly; expected 2 spaces, found 3
 36 | ERROR   | [x] Inline comments must end in full-stops, exclamation marks, question marks, colons, or closing parentheses
 41 | ERROR   | [x] Whitespace found at end of line
 42 | ERROR   | [x] Inline comments must end in full-stops, exclamation marks, question marks, colons, or closing parentheses
 44 | ERROR   | [x] Expected 1 space after FOREACH keyword; 0 found
 46 | ERROR   | [x] Expected 1 space after IF keyword; 0 found
 46 | ERROR   | [x] Inline control structures are not allowed
 50 | ERROR   | [x] Whitespace found at end of line
 51 | ERROR   | [x] Expected 1 blank line after function; 2 found
 55 | WARNING | [ ] Format should be "* Implements hook_foo().", "* Implements hook_foo_BAR_ID_bar() for xyz_bar().",, "* Implements hook_foo_BAR_ID_bar() for xyz-bar.html.twig.", "* Implements hook_foo_BAR_ID_bar()
    |         |     for xyz-bar.tpl.php.", or "* Implements hook_foo_BAR_ID_bar() for block templates."
 55 | ERROR   | [x] Doc comment short description must end with a full stop
 57 | ERROR   | [x] Additional blank lines found at end of doc comment
 63 | ERROR   | [x] Expected 1 space after IF keyword; 0 found
 73 | ERROR   | [x] Line indented incorrectly; expected 2 spaces, found 4
 73 | ERROR   | [x] Closing brace indented incorrectly; expected 2 spaces, found 4
 74 | ERROR   | [x] Expected 1 newline at end of file; 0 found
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 34 MARKED SNIFF VIOLATIONS AUTOMATICALLY
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Time: 221ms; Memory: 6MB


**phpstan --level=5 analyze web/modules/custom**
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ -------------------------------------------------------------------------------------------- 
  Line   lbd_lib/lbd_lib.module                                                                      
 ------ -------------------------------------------------------------------------------------------- 
  16     Call to an undefined method Drupal\Core\Entity\EntityInterface::getType().                  
  21     Access to an undefined property Drupal\Core\Entity\EntityInterface::$title.                 
  21     Parameter #2 ...$values of function sprintf expects bool|float|int|string|null, The given.  
  34     Function lbd_next_dootronic_id() has invalid return type The.                               
  50     Function lbd_next_dootronic_id() should return The but returns int<1, max>.                 
 ------ -------------------------------------------------------------------------------------------- 


                                                                                                                        
 [ERROR] Found 5 errors

**Comment by jrosgiralt** [comment]
Runs clean now:

    gitpod@labdoo3-web:/var/www/html$ ./vendor/bin/phpcs --standard="Drupal,DrupalPractice" --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md,yml web/modules/custom
    gitpod@labdoo3-web:/var/www/html$

**Comment by greggmarshall** [comment]
One down, now for phpstan, 

````
phpstan --level=5 analyze web/modules/custom
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ -------------------------------------------------------------------------------- 
  Line   lbd_lib/lbd_lib.module                                                          
 ------ -------------------------------------------------------------------------------- 
  15     Call to an undefined method Drupal\Core\Entity\EntityInterface::getType().      
  20     Access to an undefined property Drupal\Core\Entity\EntityInterface::$title.     
  48     Function lbd_next_dootronic_id() should return string but returns int<1, max>.  
 ------ -------------------------------------------------------------------------------- 


                                                                                                                        
 [ERROR] Found 3 errors                                                                                                 
                                                            
````

**Comment by greggmarshall** [comment]
I spent a couple of  minutes to resolve the PHPStan errors reported

As you last left the module
phpstan --level=5 analyze web/modules/custom
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ --------------------------------------------------------------------------------------------------------------- 
  Line   lbd_lib/lbd_lib.module                                                                                         
 ------ --------------------------------------------------------------------------------------------------------------- 
  20     Property Drupal\node\NodeInterface::$title (Drupal\Core\Field\FieldItemListInterface) does not accept string.  
  48     Function lbd_next_dootronic_id() should return string but returns int<1, max>.                                 
 ------ --------------------------------------------------------------------------------------------------------------- 

 [ERROR] Found 2 errors


Switching to Drupal\node\NodeInterface

phpstan --level=5 analyze web/modules/custom
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ --------------------------------------------------------------------------------------------------------------- 
  Line   lbd_lib/lbd_lib.module                                                                                         
 ------ --------------------------------------------------------------------------------------------------------------- 
  20     Property Drupal\node\NodeInterface::$title (Drupal\Core\Field\FieldItemListInterface) does not accept string.  
  48     Function lbd_next_dootronic_id() should return string but returns int<1, max>.                                 
 ------ --------------------------------------------------------------------------------------------------------------- 

 [ERROR] Found 2 errors
 
 
 Switching to $entity->set('title', sprintf("%09d", $did)) and adding strval() to the return statement
 
phpstan --level=5 analyze web/modules/custom
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 [OK] No errors

**Comment by greggmarshall** [comment]
My last change fixed PHPStan but generated errors when blocks were edited, so I switched from hook_entity_presave to hook_ENTITY_TYPE_presave to only process nodes.

**Review by greggmarshall — APPROVED** [review]

**Comment by jrosgiralt** [comment]
Thank you, this looks good.

**Pull request merged**
